apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Minimal 2 pod sesuai requirement
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Menggunakan image nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"   # Memory request untuk HPA calculation
            cpu: "250m"      # CPU request untuk stabilitas
          limits:
            memory: "128Mi"  # Memory limit untuk mencegah overconsumption
            cpu: "500m"      # CPU limit untuk mencegah overconsumption
        # Health checks untuk memastikan pod telah ready
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5